// Catálogo geográfico El Salvador — DTE Hacienda

export const DEPARTAMENTOS = [
  { codigo: '01', nombre: 'Ahuachapán' },
  { codigo: '02', nombre: 'Santa Ana' },
  { codigo: '03', nombre: 'Sonsonate' },
  { codigo: '04', nombre: 'Chalatenango' },
  { codigo: '05', nombre: 'La Libertad' },
  { codigo: '06', nombre: 'San Salvador' },
  { codigo: '07', nombre: 'Cuscatlán' },
  { codigo: '08', nombre: 'La Paz' },
  { codigo: '09', nombre: 'Cabañas' },
  { codigo: '10', nombre: 'San Vicente' },
  { codigo: '11', nombre: 'Usulután' },
  { codigo: '12', nombre: 'San Miguel' },
  { codigo: '13', nombre: 'Morazán' },
  { codigo: '14', nombre: 'La Unión' },
]

export const MUNICIPIOS_POR_DEPTO: Record<string, { codigo: string; nombre: string }[]> = {
  '01': [
    { codigo: '01', nombre: 'Ahuachapán' },
    { codigo: '02', nombre: 'Apaneca' },
    { codigo: '03', nombre: 'Atiquizaya' },
    { codigo: '04', nombre: 'Concepción de Ataco' },
    { codigo: '05', nombre: 'El Refugio' },
    { codigo: '06', nombre: 'Guaymango' },
    { codigo: '07', nombre: 'Jujutla' },
    { codigo: '08', nombre: 'San Francisco Menéndez' },
    { codigo: '09', nombre: 'San Lorenzo' },
    { codigo: '10', nombre: 'San Pedro Puxtla' },
    { codigo: '11', nombre: 'Tacuba' },
    { codigo: '12', nombre: 'Turín' },
  ],
  '02': [
    { codigo: '01', nombre: 'Santa Ana' },
    { codigo: '02', nombre: 'Candelaria de la Frontera' },
    { codigo: '03', nombre: 'Chalchuapa' },
    { codigo: '04', nombre: 'Coatepeque' },
    { codigo: '05', nombre: 'El Congo' },
    { codigo: '06', nombre: 'El Porvenir' },
    { codigo: '07', nombre: 'Masahuat' },
    { codigo: '08', nombre: 'Metapán' },
    { codigo: '09', nombre: 'San Antonio Pajonal' },
    { codigo: '10', nombre: 'San Sebastián Salitrillo' },
    { codigo: '11', nombre: 'Santa Rosa Guachipilín' },
    { codigo: '12', nombre: 'Santiago de la Frontera' },
    { codigo: '13', nombre: 'Texistepeque' },
  ],
  '03': [
    { codigo: '01', nombre: 'Sonsonate' },
    { codigo: '02', nombre: 'Acajutla' },
    { codigo: '03', nombre: 'Armenia' },
    { codigo: '04', nombre: 'Caluco' },
    { codigo: '05', nombre: 'Cuisnahuat' },
    { codigo: '06', nombre: 'Izalco' },
    { codigo: '07', nombre: 'Juayúa' },
    { codigo: '08', nombre: 'Nahuizalco' },
    { codigo: '09', nombre: 'Nahulingo' },
    { codigo: '10', nombre: 'Salcoatitán' },
    { codigo: '11', nombre: 'San Antonio del Monte' },
    { codigo: '12', nombre: 'San Julián' },
    { codigo: '13', nombre: 'Santa Catarina Masahuat' },
    { codigo: '14', nombre: 'Santa Isabel Ishuatán' },
    { codigo: '15', nombre: 'Santo Domingo de Guzmán' },
    { codigo: '16', nombre: 'Sonzacate' },
  ],
  '04': [
    { codigo: '01', nombre: 'Chalatenango' },
    { codigo: '02', nombre: 'Agua Caliente' },
    { codigo: '03', nombre: 'Arcatao' },
    { codigo: '04', nombre: 'Azacualpa' },
    { codigo: '05', nombre: 'Cancasque' },
    { codigo: '06', nombre: 'Citalá' },
    { codigo: '07', nombre: 'Comalapa' },
    { codigo: '08', nombre: 'Concepción Quezaltepeque' },
    { codigo: '09', nombre: 'Dulce Nombre de María' },
    { codigo: '10', nombre: 'El Carrizal' },
    { codigo: '11', nombre: 'El Paraíso' },
    { codigo: '12', nombre: 'La Laguna' },
    { codigo: '13', nombre: 'La Palma' },
    { codigo: '14', nombre: 'La Reina' },
    { codigo: '15', nombre: 'Las Vueltas' },
    { codigo: '16', nombre: 'Nombre de Jesús' },
    { codigo: '17', nombre: 'Nueva Concepción' },
    { codigo: '18', nombre: 'Nueva Trinidad' },
    { codigo: '19', nombre: 'Ojos de Agua' },
    { codigo: '20', nombre: 'Potonico' },
    { codigo: '21', nombre: 'San Antonio de la Cruz' },
    { codigo: '22', nombre: 'San Antonio Los Ranchos' },
    { codigo: '23', nombre: 'San Fernando' },
    { codigo: '24', nombre: 'San Francisco Lempa' },
    { codigo: '25', nombre: 'San Francisco Morazán' },
    { codigo: '26', nombre: 'San Ignacio' },
    { codigo: '27', nombre: 'San Isidro Labrador' },
    { codigo: '28', nombre: 'San Luis del Carmen' },
    { codigo: '29', nombre: 'San Miguel de Mercedes' },
    { codigo: '30', nombre: 'San Rafael' },
    { codigo: '31', nombre: 'Santa Rita' },
    { codigo: '32', nombre: 'Tejutla' },
  ],
  '05': [
    { codigo: '01', nombre: 'Santa Tecla (Nueva San Salvador)' },
    { codigo: '02', nombre: 'Antiguo Cuscatlán' },
    { codigo: '03', nombre: 'Chiltiupán' },
    { codigo: '04', nombre: 'Ciudad Arce' },
    { codigo: '05', nombre: 'Colon' },
    { codigo: '06', nombre: 'Comacarán' },
    { codigo: '07', nombre: 'Huizúcar' },
    { codigo: '08', nombre: 'Jayaque' },
    { codigo: '09', nombre: 'Jicalapa' },
    { codigo: '10', nombre: 'La Libertad' },
    { codigo: '11', nombre: 'Nuevo Cuscatlán' },
    { codigo: '12', nombre: 'Opico' },
    { codigo: '13', nombre: 'Quezaltepeque' },
    { codigo: '14', nombre: 'Sacacoyo' },
    { codigo: '15', nombre: 'San José Villanueva' },
    { codigo: '16', nombre: 'San Juan Opico' },
    { codigo: '17', nombre: 'San Matías' },
    { codigo: '18', nombre: 'San Pablo Tacachico' },
    { codigo: '19', nombre: 'Talnique' },
    { codigo: '20', nombre: 'Tamanique' },
    { codigo: '21', nombre: 'Teotepeque' },
    { codigo: '22', nombre: 'Tepecoyo' },
    { codigo: '23', nombre: 'Zaragoza' },
  ],
  '06': [
    { codigo: '01', nombre: 'San Salvador' },
    { codigo: '02', nombre: 'Aguilares' },
    { codigo: '03', nombre: 'Apopa' },
    { codigo: '04', nombre: 'Ayutuxtepeque' },
    { codigo: '05', nombre: 'Cuscatancingo' },
    { codigo: '06', nombre: 'Delgado' },
    { codigo: '07', nombre: 'El Paisnal' },
    { codigo: '08', nombre: 'Guazapa' },
    { codigo: '09', nombre: 'Ilopango' },
    { codigo: '10', nombre: 'Mejicanos' },
    { codigo: '11', nombre: 'Nejapa' },
    { codigo: '12', nombre: 'Panchimalco' },
    { codigo: '13', nombre: 'Rosario de Mora' },
    { codigo: '14', nombre: 'San Marcos' },
    { codigo: '15', nombre: 'San Martín' },
    { codigo: '16', nombre: 'Santiago Texacuangos' },
    { codigo: '17', nombre: 'Santo Tomás' },
    { codigo: '18', nombre: 'Soyapango' },
    { codigo: '19', nombre: 'Tonacatepeque' },
  ],
  '07': [
    { codigo: '01', nombre: 'Cojutepeque' },
    { codigo: '02', nombre: 'El Carmen' },
    { codigo: '03', nombre: 'El Rosario' },
    { codigo: '04', nombre: 'Monte San Juan' },
    { codigo: '05', nombre: 'Oratorio de Concepción' },
    { codigo: '06', nombre: 'San Bartolomé Perulapía' },
    { codigo: '07', nombre: 'San Cristóbal' },
    { codigo: '08', nombre: 'San José Guayabal' },
    { codigo: '09', nombre: 'San Pedro Perulapán' },
    { codigo: '10', nombre: 'San Ramón' },
    { codigo: '11', nombre: 'Santa Cruz Analquito' },
    { codigo: '12', nombre: 'Santa Cruz Michapa' },
    { codigo: '13', nombre: 'Suchitoto' },
    { codigo: '14', nombre: 'San Juan Tepezontes' },
  ],
  '08': [
    { codigo: '01', nombre: 'Zacatecoluca' },
    { codigo: '02', nombre: 'Cuyultitán' },
    { codigo: '03', nombre: 'El Rosario' },
    { codigo: '04', nombre: 'Jerusalén' },
    { codigo: '05', nombre: 'Mercedes La Ceiba' },
    { codigo: '06', nombre: 'Olocuilta' },
    { codigo: '07', nombre: 'Paraíso de Osorio' },
    { codigo: '08', nombre: 'San Antonio Masahuat' },
    { codigo: '09', nombre: 'San Emigdio' },
    { codigo: '10', nombre: 'San Francisco Chinameca' },
    { codigo: '11', nombre: 'San Juan Nonualco' },
    { codigo: '12', nombre: 'San Juan Talpa' },
    { codigo: '13', nombre: 'San Juan Tepezontes' },
    { codigo: '14', nombre: 'San Luis La Herradura' },
    { codigo: '15', nombre: 'San Luis Talpa' },
    { codigo: '16', nombre: 'San Miguel Tepezontes' },
    { codigo: '17', nombre: 'San Pedro Masahuat' },
    { codigo: '18', nombre: 'San Pedro Nonualco' },
    { codigo: '19', nombre: 'San Rafael Obrajuelo' },
    { codigo: '20', nombre: 'Santa María Ostuma' },
    { codigo: '21', nombre: 'Santiago Nonualco' },
    { codigo: '22', nombre: 'Tapalhuaca' },
  ],
  '09': [
    { codigo: '01', nombre: 'Sensuntepeque' },
    { codigo: '02', nombre: 'Cinquera' },
    { codigo: '03', nombre: 'Dolores' },
    { codigo: '04', nombre: 'Guacotecti' },
    { codigo: '05', nombre: 'Ilobasco' },
    { codigo: '06', nombre: 'Jutiapa' },
    { codigo: '07', nombre: 'San Isidro' },
    { codigo: '08', nombre: 'Tejutepeque' },
    { codigo: '09', nombre: 'Victoria' },
  ],
  '10': [
    { codigo: '01', nombre: 'San Vicente' },
    { codigo: '02', nombre: 'Apastepeque' },
    { codigo: '03', nombre: 'Guadalupe' },
    { codigo: '04', nombre: 'San Cayetano Istepeque' },
    { codigo: '05', nombre: 'San Esteban Catarina' },
    { codigo: '06', nombre: 'San Ildefonso' },
    { codigo: '07', nombre: 'San Lorenzo' },
    { codigo: '08', nombre: 'San Sebastián' },
    { codigo: '09', nombre: 'Santa Clara' },
    { codigo: '10', nombre: 'Santo Domingo' },
    { codigo: '11', nombre: 'Tecoluca' },
    { codigo: '12', nombre: 'Tepetitán' },
    { codigo: '13', nombre: 'Verapaz' },
  ],
  '11': [
    { codigo: '01', nombre: 'Usulután' },
    { codigo: '02', nombre: 'Alegría' },
    { codigo: '03', nombre: 'Berlín' },
    { codigo: '04', nombre: 'California' },
    { codigo: '05', nombre: 'Concepción Batres' },
    { codigo: '06', nombre: 'El Triunfo' },
    { codigo: '07', nombre: 'Ereguayquín' },
    { codigo: '08', nombre: 'Estanzuelas' },
    { codigo: '09', nombre: 'General Pedro Ávila' },
    { codigo: '10', nombre: 'Jiquilisco' },
    { codigo: '11', nombre: 'Jucuapa' },
    { codigo: '12', nombre: 'Jucuarán' },
    { codigo: '13', nombre: 'Mercedes Umaña' },
    { codigo: '14', nombre: 'Nueva Granada' },
    { codigo: '15', nombre: 'Ozatlán' },
    { codigo: '16', nombre: 'Puerto El Triunfo' },
    { codigo: '17', nombre: 'San Agustín' },
    { codigo: '18', nombre: 'San Buenaventura' },
    { codigo: '19', nombre: 'San Dionisio' },
    { codigo: '20', nombre: 'San Francisco Javier' },
    { codigo: '21', nombre: 'Santa Elena' },
    { codigo: '22', nombre: 'Santa María' },
    { codigo: '23', nombre: 'Santiago de María' },
    { codigo: '24', nombre: 'Tecapán' },
  ],
  '12': [
    { codigo: '01', nombre: 'San Miguel' },
    { codigo: '02', nombre: 'Carolina' },
    { codigo: '03', nombre: 'Chapeltique' },
    { codigo: '04', nombre: 'Chinameca' },
    { codigo: '05', nombre: 'Chirilagua' },
    { codigo: '06', nombre: 'Ciudad Barrios' },
    { codigo: '07', nombre: 'Comacarán' },
    { codigo: '08', nombre: 'El Tránsito' },
    { codigo: '09', nombre: 'Lolotique' },
    { codigo: '10', nombre: 'Moncagua' },
    { codigo: '11', nombre: 'Nueva Guadalupe' },
    { codigo: '12', nombre: 'Nuevo Edén de San Juan' },
    { codigo: '13', nombre: 'Quelepa' },
    { codigo: '14', nombre: 'San Antonio' },
    { codigo: '15', nombre: 'San Gerardo' },
    { codigo: '16', nombre: 'San Jorge' },
    { codigo: '17', nombre: 'San Luis de la Reina' },
    { codigo: '18', nombre: 'San Rafael Oriente' },
    { codigo: '19', nombre: 'Sesori' },
    { codigo: '20', nombre: 'Uluazapa' },
  ],
  '13': [
    { codigo: '01', nombre: 'San Francisco Gotera' },
    { codigo: '02', nombre: 'Arambala' },
    { codigo: '03', nombre: 'Cacaopera' },
    { codigo: '04', nombre: 'Corinto' },
    { codigo: '05', nombre: 'Chilanga' },
    { codigo: '06', nombre: 'Delicias de Concepción' },
    { codigo: '07', nombre: 'El Divisadero' },
    { codigo: '08', nombre: 'El Rosario' },
    { codigo: '09', nombre: 'Gualococti' },
    { codigo: '10', nombre: 'Guatajiagua' },
    { codigo: '11', nombre: 'Joateca' },
    { codigo: '12', nombre: 'Jocoaitique' },
    { codigo: '13', nombre: 'Jocoro' },
    { codigo: '14', nombre: 'Lolotiquillo' },
    { codigo: '15', nombre: 'Meanguera' },
    { codigo: '16', nombre: 'Osicala' },
    { codigo: '17', nombre: 'Perquín' },
    { codigo: '18', nombre: 'San Carlos' },
    { codigo: '19', nombre: 'San Fernando' },
    { codigo: '20', nombre: 'San Isidro' },
    { codigo: '21', nombre: 'San Simón' },
    { codigo: '22', nombre: 'Sensembra' },
    { codigo: '23', nombre: 'Sociedad' },
    { codigo: '24', nombre: 'Torola' },
    { codigo: '25', nombre: 'Yamabal' },
    { codigo: '26', nombre: 'Yoloaiquín' },
  ],
  '14': [
    { codigo: '01', nombre: 'La Unión' },
    { codigo: '02', nombre: 'Anamorós' },
    { codigo: '03', nombre: 'Bolívar' },
    { codigo: '04', nombre: 'Concepción de Oriente' },
    { codigo: '05', nombre: 'Conchagua' },
    { codigo: '06', nombre: 'El Carmen' },
    { codigo: '07', nombre: 'El Sauce' },
    { codigo: '08', nombre: 'Intipucá' },
    { codigo: '09', nombre: 'Lislique' },
    { codigo: '10', nombre: 'Meanguera del Golfo' },
    { codigo: '11', nombre: 'Nueva Esparta' },
    { codigo: '12', nombre: 'Pasaquina' },
    { codigo: '13', nombre: 'Polorós' },
    { codigo: '14', nombre: 'San Alejo' },
    { codigo: '15', nombre: 'San José' },
    { codigo: '16', nombre: 'Santa Rosa de Lima' },
    { codigo: '17', nombre: 'Yayantique' },
    { codigo: '18', nombre: 'Yucuaiquín' },
  ],
}

// Actividades económicas frecuentes (DTE Hacienda)
export const ACTIVIDADES_ECONOMICAS = [
  { codigo: '4711', nombre: 'Venta al por menor en comercios no especializados' },
  { codigo: '4719', nombre: 'Otras actividades de venta al por menor' },
  { codigo: '4721', nombre: 'Venta al por menor de alimentos' },
  { codigo: '4772', nombre: 'Venta al por menor de productos farmacéuticos' },
  { codigo: '4781', nombre: 'Venta al por menor de alimentos en puestos de venta' },
  { codigo: '5610', nombre: 'Actividades de restaurantes y de servicio móvil' },
  { codigo: '6201', nombre: 'Actividades de programación informática' },
  { codigo: '6920', nombre: 'Actividades de contabilidad, teneduría de libros' },
  { codigo: '7010', nombre: 'Actividades de administración empresarial' },
  { codigo: '7490', nombre: 'Otras actividades profesionales' },
  { codigo: '8610', nombre: 'Actividades de hospitales' },
  { codigo: '8621', nombre: 'Actividades de medicina general' },
  { codigo: '9311', nombre: 'Gestión de instalaciones deportivas' },
  { codigo: '9321', nombre: 'Actividades de parques de atracciones' },
  { codigo: '9602', nombre: 'Peluquería y otros tratamientos de belleza' },
]
